### ISSUE TITLE
Player and GM switch doesn't sync

### ISSUE THREAD

**Issue by CepheiA2** [death-save/combat-carousel#110]
**Describe the bug**
When switching from encounter 1 to encounter 2 as GM the carousel works properly and switch the combantats, meanwhile as player do not switch and become stucked on the first combat encounter.

**To Reproduce**
1. Start a combat with some combantats as encounter 1
2. Log as gm and in another tab as a player
3. Switch the combat between encounter 1 or 2
4. See error appearing on the top of player view

**Expected behavior**
Expect player carousel sync with the GM's one.

**Environment Info (please complete the following information):**
 - Foundry Version: [0.8.9]
 - Game System / Version: [dnd5e 1.5.3]
 - Browser [e.g. chrome]
 - OS [e.g. Windows 10]

**Additional context**
If possibile will be nice to hide the carousel to players until the encounter start.

**Comment by eclarke12** [comment]
This is a core Foundry bug fixed in Version 9 https://gitlab.com/foundrynet/foundryvtt/-/issues/6049
