### ISSUE TITLE
Add End Turn Button

### ISSUE THREAD

**Issue by SabreRunner** [death-save/combat-carousel#111]
**Is your feature request related to a problem? Please describe.**
One thing I really like about the Foundry combat tracker is that every player can end their own turn. I like the carousel but it doesn't offer that functionality and I, as the guide, have to do it manually.

**Describe the solution you'd like**
Some kind of button on the carousel, available to everyone who owns the current active token, to end the turn like in the regular combat tracker.

**Describe alternatives you've considered**
Nothing except going back to the original combat tracker but I prefer the carousel.

**Comment by eclarke12** [comment]
During a Player's turn they should have an arrow on the right hand side of the Carousel to end their turn. If you are not seeing this, please reopen.
