### ISSUE TITLE
Not working correctly on v9

### ISSUE THREAD

**Issue by JamesBrandts** [death-save/combat-carousel#116]
After updating to FoundryVTT v9.238 today, the Combat Carousel is not showing anymore. The  Combat Carousel button in the sidebar is not working.  The problem is cited in the [Compatibility Spreadsheet for v9](https://docs.google.com/spreadsheets/d/e/2PACX-1vQB3hKXseLn1ROUxepiw09GYQPG8ikwZjY_Nkde9KnC9PUJA0gNWBuMIJ66iU0qokAbERQ8jF-Bwwrh/pubhtml?gid=0&single=true).

It kinda works with the following macro hook:

```js
// Renders the Combat Carousel every updateCombat, so the turns marker changes
Hooks.on('updateCombat',()=>{
  ui.combatCarousel.render(true); 
 // When it renders for the first time in a combat, it appears on the top/left corner and sometimes it's hard to drag it to other position
  if (ui.combatCarousel.position.left < 150){
    ui.combatCarousel.setPosition({left: 200});}
});
```
**Environment Info (please complete the following information):**
 - Foundry Version: [9.238]
 - Game System / Version: [dnd5e 1.5.6]
 - CC Version [0.2.3]
 - Browser [chrome]
 - OS [Windows 10]

**Comment by eclarke12** [comment]
duplicate
reported in #112 
fixed in next update
