### ISSUE TITLE
Icon is not fixed into the box in the sidebar

### ISSUE THREAD

**Issue by Fyrexian** [death-save/combat-carousel#121]
**Describe the bug**
The icon is appearing outside the icon
![image](https://user-images.githubusercontent.com/47077661/148313286-ce5540cc-b3d8-4afe-9c8e-7970d489a262.png)

**Comment by eclarke12** [comment]
What version of Foundry, Combat Carousel, what game system?

Looks like some 3rd party styling is being applied.

**Comment by VaethConner** [comment]
Foundry: V9 238
Combat Carousel: 0.2.5
DND5e (But also pathfinder 2e)

https://gitlab.com/sasmira/dnd-ui
https://gitlab.com/sasmira/pathfinder-ui

It used to fit fine before the V9 update, but now it does not when using the UIs(for both systems).

![image](https://user-images.githubusercontent.com/47077661/149646951-e181771b-662b-485c-98fc-b60478c25270.png)

**Comment by eclarke12** [comment]
This is caused by the 3rd party module https://github.com/Xbozon/rpg-styled-ui
I believe it has been resolved this this issue was opened
