### ISSUE TITLE
CSS issue with custom UI module

### ISSUE THREAD

**Issue by crymic** [death-save/combat-carousel#136]
**Describe the bug**
CSS issue with 9.x Foundry

**To Reproduce**
Tokens are bleeding over if using different uis
Also last token is not hidden.

**Expected behavior**
Should hide all that bleed over plus hide the last token.

**Screenshots**
https://cdn.discordapp.com/attachments/751524268956713092/978838681244827708/unknown.png
https://cdn.discordapp.com/attachments/751524268956713092/978843228755349544/unknown.png

**Environment Info (please complete the following information):**
 - Foundry Version: 9
 - Game System / Version: DnD 5e 1.6.1
 - CC Version 0.2.5
 - Browser Microsoft Edge
 - OS Windows 11

**Additional context**
You can easily fix most of the bleed and issues by adding
```css
#combat-carousel .splide__slider {
    height: 100%;
    padding: 0px 55px;
    overflow:hidden;
}
```
This will remove the bleed over but still the last token is present.
Looks like a new class has been added `.is-visible`, think this is probably from foundry's bootstrap.
also aria-hidden  true false is can always be taken advantage of along with tabindex.

**Comment by eclarke12** [comment]
This is an issue with the RPG Styled UI, I suggest opening an issue there https://github.com/Xbozon/rpg-styled-ui
