### ISSUE TITLE
Player Overlay Permission not working.

### ISSUE THREAD

**Issue by Duschmolll** [death-save/combat-carousel#137]
**Describe the bug**
The Player Overlay Permission is not working as intended. When selected to none, the players still can use the overlay.

**To Reproduce**
Start an encounter with the following settings: 
https://cdn.discordapp.com/attachments/751524268956713092/983502593500254208/unknown.png
Check the player's perspective and the overlay should still be available.

**Expected behavior**
The players shoudn't be able to see/use the overlay.

**Screenshots**
https://cdn.discordapp.com/attachments/751524268956713092/983502593500254208/unknown.png

**Environment Info (please complete the following information):**
 - Foundry Version:.269
 - Game System / Version: Chroniques Oubliées Contemporain v9.269.3
 - CC Version 0.2.5
 - Browser Tested on Edge
 - OS Windows 10

**Additional context**
The error might be coming from a conflict with another module.
Here is the list: 
- Better Roofs
- Combat Carousel
- Combat Numbers
- Compendium Folders
- DF Architect
- DF Settings Clarity
- Dice So Nice!
- Dice Tray
- Foundry Community Macros
- FoundryVTT Arms Reach
- Image Hover
- Levels
- lib - Color Settings
- libWrapper
- Moulinette (All free to use module by him)
- Multilevel Tokens
- Party Resources
- Perfect Vision
- Pings
- Settings Extender
- Smart Target
- socketlib
- Splatter
- Tidy UI - Game Settings
- Token Action HUD
- Turn Marker
- Wall Height
- Weather Blocker

**Comment by eclarke12** [comment]
I believe this should be resolved in Foundry VTT v10 with Combat Carousel v0.3.0. Please test after your system releases an update for v10 and report back.
