### ISSUE TITLE
Add "Begin Combat" button when Combat is on round 0

### ISSUE THREAD

**Issue by eclarke12** [death-save/combat-carousel#142]
We should add a button/behaviour for round 0 so it's clear the user will be starting combat.

Note: call `game.combat.startCombat()` to begin

**Comment by bearsy1** [comment]
I would also like to see this added! When first getting used to the carousel's gui, I often had to hover over the arrow buttons to see which one would kick-off round 1. Perhaps a different icon or different button design would help make it easier and more intuitive to quickly find the right button to click?

On a related note, one of the buttons I used frequently is no longer present -- it was the set of left and right arrow looking buttons that would change/cycle the 'active combatant' for a given round. 

Not sure if it's a foundry v10 issue or if it was removed with the recent updates to the combat carousel, but I would like to see these buttons come back if possible. For now though, clicking on the portraits to manually change/highlight the current combatant still works though, so it's not like we're completely without options.

Anyhow, thank you for the work you have put into this great module!
