### ISSUE TITLE
Carousel does not seem to survive a reload

### ISSUE THREAD

**Issue by jfrazierjr** [death-save/combat-carousel#144]
**To Reproduce**
1. select tokens
2. add combatants to the combat(I did so by right clicking and selecting the toggle combat state icon)
3. F5 or hit the browser reload button

**Expected behavior**
Combat Carousel should detect:

1. Is a combat ongoing(I ASSUME this can be done, the core game simply reloads the core game state into the combat tracker)
2. is Enable Combat Carousel checked in settings
3. displays the combat Carousel.

 

**Environment Info (please complete the following information):**
 - Foundry Version: 9.280
 - Game System / Version: D&D 1.6.1
 - CC Version 9.238
 - Browser Chrome
 - OS Windows 10]

**Additional context**
I have tried both with and without Minimal UI enabled in the manage module settings so this does not appear to be the issue.  I have quite a few modules installed, but that was the one I expected to possibly cause a collision.

Note this was on a browser window as GM.  I have NOT attempted this via a secondary player connection.  I first noticed this as I was adjusting settings in the config working on some changes to other modules settings while a combat was ongoing.

**Comment by eclarke12** [comment]
It's possible the Carousel is just minimised on load. If you click the Carousel button in the scene controls does it show up?

**Comment by eclarke12** [comment]
If this is still happening in v0.3.0+ (Foundry VTT v10) please reopen
