### ISSUE TITLE
Combat Carousel Not Automatically Updating Changing Health Values

### ISSUE THREAD

**Issue by AquaDragon33** [death-save/combat-carousel#149]
**Describe the bug**
When a token's health is updated, the Combat Carousel will not automatically reflect the new health value. However, if the tracker is refreshed in some way (such as by going to the next turn), then all the HP values will successfully update as expected.

**To Reproduce**
1. Attach a token to combat so it appears in the Combat Carousel
2. Change the health on the token 
3. Notice that it does not update on the CC
4. Refresh the CC and notice that the token HP is now accurate there

**Expected behavior**
The token HP should be reflected in the combat carousel automatically without refreshing it

**Screenshots**
![unknown](https://user-images.githubusercontent.com/11086640/189507270-3e8f60fa-a008-477d-ade2-4950abf6d6fc.png)

**Environment Info (please complete the following information):**
 - Foundry Version: 285
 - Game System / Version: dnd5e
 - CC Version 0.3.0
 - OS Windows 11

**Additional context**
Thanks for making such a cool module!

**Comment by Jacob-Lisner** [comment]
I just ran into this bug too (for me it was only occurring with PCs). No modules running, same specs except v10.286.
