### ISSUE TITLE
PF2e - Token Tool bar above actor on carousel buried or missing

### ISSUE THREAD

**Issue by CaptainRoBear** [death-save/combat-carousel#156]
![image](https://user-images.githubusercontent.com/81845234/214353574-7ba00189-d7b0-48cc-a9c3-f9824abbf358.png)

The tool bar where you could declare a token dead or remove them from the initiative all together is now missing or hidden behind these nameplates above the their image on the carousel.

 - Foundry Version: 10 / 291
 - Game System / Version: PF2e 4.6.8
 - CC Version [e.g. 0.3.0] Chrome
 - OS [e.g. Windows 10] Win 10

**Comment by eclarke12** [comment]
@CaptainRoBear do you have any UI mods installed? It looks like there's something changing the layout a bit. I will say CC hasn't had an update in awhile so it's possible this is related to changes within the pf2e system itself that require updates in CC.

**Comment by CaptainRoBear** [comment]
You're correct. This was caused by PF2e Dorako UI
