### ISSUE TITLE
Overlay Properties do not work in DnD5e system

### ISSUE THREAD

**Issue by arriagagary** [death-save/combat-carousel#158]
For Overlay Properties, I can change the icon fine. But no matter what I try to set the value to, it never works. I've tried all sort of different combinations of strings (including or excluding "data.", etc.), targeting all of the different attributes, including ones that definitely work in macros and other modules, but the value is always blank for me.

I've made sure to disable all other modules during my testing, so it was not caused by any issues with other mods and this one together.

This is the case for both versions 0.3.0 and 0.3.1
I tested in 0.2.5 and it *DOES* work in that version!

![CombatCarousel_OverlayProperty_NotShowing](https://user-images.githubusercontent.com/6765269/218866507-5c215474-2b19-46b2-9c6d-635d207b38ae.png)

**Comment by eclarke12** [comment]
Hi @arriagagary, the property values changed with v10 of Foundry's new data model. You can ask on the system channel on the main foundry discord to discover what they are for various things, but for your example of `AC` the value would be `system.attributes.ac.value`
