### ISSUE TITLE
Bug: When using CUB. Selecting the Skull doesn't properly apply the "dead" condition. Conflicting with "Award XP"

### ISSUE THREAD

**Issue by ExW-Tritone** [death-save/combat-carousel#53]
Exactly what it says if you mark as defeated in the carousel it doesn't update from unconscious in the combat tracker. When you end combat with all combatants marked defeated in just the carousel "award XP" doesn't function properly.

**Comment by Darshyne** [comment]
Same for me

**Comment by eclarke12** [comment]
This is two issues in one:
1. Combatants marked as defeated in CC not correctly marking in the normal tracker: seems to be fixed in 0.2.1 (coming soon) -- please test in 0.2.1 when it releases and report back
2. Ending combat not giving Award XP prompt see: #57
