### ISSUE TITLE
CC doesn't appear automatically when starting combat (alpha 2   v 0.2.0)

### ISSUE THREAD

**Issue by justmark** [death-save/combat-carousel#54]
In the public version of CC, the combat strip appears when combat is initiated allowing users to roll for their individual initiative, before combat starts.

With 0.2.0 I am finding that the strip doesn't appear automatically.  I have to click the CC icon on the left panel to get the strip to appear.  Out of combat the CC icon is present, and I can click it to toggle the small triangle on the icon (up vs. down).  Depending on the state of this triangle, I will either need to click the CC icon once or twice to get the initiative strip to appear.

Here is my screen when I initiate combat.  CC hasn't appeared.  I've included the Combat Tracker to show the current state:

<img width="935" alt="image" src="https://user-images.githubusercontent.com/575270/106037512-c8851500-60a4-11eb-8940-710f0d3f1aa1.png">

After clicking the CC icon on the left TWICE, I then get:

<img width="861" alt="image" src="https://user-images.githubusercontent.com/575270/106037593-e5214d00-60a4-11eb-9ff8-b09323829603.png">

After this things seem to run normally.

**Comment by Darshyne** [comment]
Same for me i must click twice
