### ISSUE TITLE
0.2.0 Alpha - Trashcan button (Delete Encounter) skips confirmation dialogue

### ISSUE THREAD

**Issue by megahead11** [death-save/combat-carousel#57]
**Describe the bug**
Clicking on the trashcan button (Delete Encounter) will end any combat (started or not) without popping up the foundry standard confirmation dialogue. This can lead to accidentally ending encounters via mis-click.  Standard turn tracker still behaves as expected.

**To Reproduce**
1. Enable combat carousel
2. Add tokens to combat and begin combat.
3. Click the "Trashcan" in the carousel. You will see the encounter will end, but there will be no confirmation to do so.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome Beta/Electron (tested on both)
 - Version 89.0.4389.72 (Beta)/Electron Foundry 0.7.9

**Comment by Darshyne** [comment]
Same for me
