### ISSUE TITLE
Can't roll initiative from the carousel

### ISSUE THREAD

**Issue by kamcknig** [death-save/combat-carousel#64]
**Describe the bug**
When starting a combat and clicking the button to roll initiative within the carousel interface, the intiiative is not rolled and the browser console displays an error

**To Reproduce**
1. Add combatants to a combat
2. Start the combat
3. Roll initiative by clicking red die for the combatant in the carousel

**Expected behavior**
Initiative is rolled and shown on combatant's carousel card

**Screenshots**
![2021-06-12 15_35_12-Foundry Virtual Tabletop • A Standalone Virtual Tabletop Application](https://user-images.githubusercontent.com/705490/121787503-5c5b0780-cb94-11eb-8654-2ab1b06c1b9c.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by eclarke12** [comment]
What version of Foundry and Combat Carousel?

**Comment by kyle-mcknight** [comment]
Hi!

0.8.6

**Comment by eclarke12** [comment]
This is resolved in 0.2.1 (coming soon)
