### ISSUE TITLE
Add an option to filter which Active Effects are displayed on cards

### ISSUE THREAD

**Issue by SabreRunner** [death-save/combat-carousel#73]
**Describe the bug**
When I open the carousel, all DA Effects are displayed on the portrait. Even the passive ones. Even the inactive ones. One of my players likes to play around with making them. Now their portrait is almost completely blocked.

**To Reproduce**
1. Have Dynamic Active Effects on.
2. Create several effects, active, passive, and inactive ones.
3. Activate carousel.

**Expected behavior**
I expect to see the active effects only.

**Environment Info (please complete the following information):**
 - Foundry Version: 0.8.8
 - Game System / Version: dnd5e 1.3.6
 - CC Version 0.2.1
 - Built-in
 - OS Windows 10

![Screenshot 2021-07-07 183743](https://user-images.githubusercontent.com/10673434/124788908-7b11ab80-df52-11eb-8c94-96876bb2342e.png)
![Screenshot 2021-07-07 183758](https://user-images.githubusercontent.com/10673434/124788914-7baa4200-df52-11eb-8d8c-50fa59e9a17a.png)

**Comment by eclarke12** [comment]
Also add an option for `None` - no effects displayed

**Comment by Merudo** [comment]
At the very least, inactive effects should not be shown by default.

**Comment by eclarke12** [comment]
Closed by #100
