### ISSUE TITLE
No longer works with GURPS Game-Aid

### ISSUE THREAD

**Issue by Grayscalae** [death-save/combat-carousel#79]
As per the title, CC no longer works with the GURPS Game-Aid system: https://github.com/crnormand/gurps

**Environment Info (please complete the following information):**
 - Foundry Version:  0.8.8
 - Game System / Version: GGA 0.11.4
 - CC Version 0.2.1
 - Standalone FVTT
 - OS: Windows 10

Cheers.

**Comment by eclarke12** [comment]
Fixed by #100
