### ISSUE TITLE
Add setting for token selection when active combatant changes

### ISSUE THREAD

**Issue by grovell** [death-save/combat-carousel#80]
First of, thank you for this amazing module! it helps to make combat a breeze for me as a DM and has saved me large ammounts of time during combats.

I was wondering if it would be possible to add a checkbox to disable tokens being automatically selected as a DM when advancing turns? I dont believe the carousel used to do this in previous versions and having a toggle would be much appreciated, as it can cause a bit of confusion with DM vision. Thanks!

**Comment by eclarke12** [comment]
Closed by #100
