### ISSUE TITLE
Hidden Combatants show up to players

### ISSUE THREAD

**Issue by eclarke12** [death-save/combat-carousel#84]
https://discord.com/channels/751505150862164129/804042654211244092/863979663608774656

**Comment by mtvjr** [comment]
I can confirm that I am experiencing the same bug.

**Comment by Dilzi** [comment]
I'm experiencing this too, it ruined a really fun surprise for the players last night.

**Comment by eclarke12** [comment]
Really sorry about this. I believe the root cause is this bug in core (I just opened): https://gitlab.com/foundrynet/foundryvtt/-/issues/5705

I will update Combat Carousel in the next few weeks to prevent this happening though.
