### ISSUE TITLE
HP handling doesn't work well with temphp & tempmax (5e)

### ISSUE THREAD

**Issue by DarKDinDoN** [death-save/combat-carousel#86]
**Describe the bug**
Combat carousel is displaying the wrong amount of HP for npcs

**To Reproduce**
1. Add an unliked npc to the combat tracker
2. Add 10 temp hp
3. Add 10 temp max hp 
4. Add 10 HP to the creature (to reflect the added 10 temp max hp)
5. Set temp hp to 0
6. Set temp max hp to 0
7. Combat carousel is displaying 10 hp extra (temp hp I guess)
8. It's like combat carousel is not refreshing when some values change

**Expected behavior**
HP bar should display the right amount of HP

**Screenshots**
![image](https://user-images.githubusercontent.com/1687854/126081447-3f1d5c60-4018-4dcf-82b2-f125a5d5711c.png)

**Environment Info (please complete the following information):**
 - Foundry Version: 0.8.8
 - Game System / Version: 5e 1.3.6
 - CC Version: 0.2.1
 - Browser: Chrome
 - OS: Windows 10

**Comment by eclarke12** [comment]
I've validated this issue however due to system-specific customisations the 5e system does to the token HP and bars I'm not sure I'll be able to implement this in the near future.

**Comment by eclarke12** [comment]
Actually I might have solved this...
