### ISSUE TITLE
Carousel can get hidden under other UI elements

### ISSUE THREAD

**Issue by kainpen** [death-save/combat-carousel#90]
**Describe the bug**

Not sure if this a bug or feature that need to be adjust, But I can no longer move the combat carousel the place you click to drag and move it, end up under the tile on right side of foundry and, it can no longer be clicked. I am not sure how it end up in that spot after my game had crashed.  Only the foundry button can be clicked You can force it to get stuck by dragging it in to that area and drop. Uninstalling Carousel and reinstalling would not fix the issues. 

**To Reproduce**
1. Go to 'the option to move the carousel'
2. Click on 'click it and drag it to the Left hand of the screen side and drop behind the buttons that foundry normally has '
3. there is no error you can not any longer move the carousel. 

**Expected behavior**
Allow the combat carousel to be moved from any spot on you can click it.

**Screenshots**
If applicable, add screenshots to help explain your problem. including
![Capture](https://user-images.githubusercontent.com/85844266/127749046-e710d624-45bb-491b-879b-68054aca0923.PNG)
 screening 

This is one showing that the section you click end up behind buttons or tiles.
![Capture 2](https://user-images.githubusercontent.com/85844266/127749223-620bf741-3976-423f-8a41-a3d3d35e799d.PNG)

**Environment Info (please complete the following information):**
 - Foundry Version: [ 0.8.8]
 - Game System / Version: [Pathfinder 2nd edition 2.10.1.7007]
 - CC Version [0.2.1]
 - Browser [chrome]
 - OS [Windows 10]

**Additional context**

**Comment by eclarke12** [comment]
If you right-click the combat carousel icon in the scene controls it should reset its position.

**Comment by kainpen** [comment]
Thanks that worked.

**Comment by eclarke12** [comment]
Keeping this open to see if it's possible to add a way to ensure the Carousel is on top of other elements when its focused or via some interaction.
